contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.contact_form, name='contact_page'),


]

portfolio_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from abilitys import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('projects/', include('projects.urls')),
    path('contact/', include('contact.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



projects/urls.py
from django.urls import path
from . import views


app_name = 'projects'

urlpatterns = [
    path('', views.project_list, name='project_list'),
    path('<int:project_id>/', views.project_detail, name='project_detail'),
    path('signup/', views.signupuser, name='signup'),
    path('logout/', views.logoutuser, name='logout'),
    path('login/', views.loginuser, name='login'),
]

abilitys/models.py
from django.db import models


class Ability(models.Model):
    title = models.CharField(max_length=30)
    description = models.CharField(max_length=400)
    image = models.ImageField(upload_to='abilitys/images')

    def __str__(self):
        return self.title



contact/models.py
from django.db import models

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

projects/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=30)
    description = models.TextField()
    date_completed = models.DateField()
    image = models.ImageField(upload_to='projects/images')
    download_link = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.title

contact/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label='Your Name', max_length=100)
    email = forms.EmailField(label='Your Email')
    message = forms.CharField(label='Message', widget=forms.Textarea)

projects/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password1']

abilitys/views.py
from django.shortcuts import render
from .models import Ability

def home(request):
    abilitys = Ability.objects.all()
    return render(request, 'abilitys/home.html', {'abilitys': abilitys})




contact/views.py
from django.shortcuts import render
from .models import Contact
from .forms import ContactForm



def contact_form(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            return render(request, 'contact/thank_you.html')
    else:
        form = ContactForm()
    return render(request, 'contact/contact_page.html', {'form': form})

projects/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from .models import Project
from django.contrib.auth.models import User




def project_list(request):
    projects = Project.objects.all()
    return render(request, 'projects/project_list.html', {'projects': projects})

def project_detail(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    return render(request, 'projects/project_detail.html', {'project': project})

def signupuser(request):
    if request.method == 'GET':
        return render(request, 'projects/signupuser.html', {'form': UserCreationForm()})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(
                    request.POST['username'],
                    password=request.POST['password1']
                )
                user.save()
                login(request, user)
                return redirect('home')
            except IntegrityError:
                return render(request, 'projects/signupuser.html', {'form': UserCreationForm(),
                                                                    'error': 'Пользователь с таким именем уже существует!'})
        else:
            return render(request, 'projects/signupuser.html',
                          {'form': UserCreationForm(),
                           'error': 'Пароли не совпали!'})


def loginuser(request):
    if request.method == 'GET':
        return render(request, 'projects/loginuser.html', {'form': AuthenticationForm()})
    else:
        user = authenticate(request, username=request.POST['username'],
                            password=request.POST['password'])
        if user is None:
            return render(request, 'projects/loginuser.html',
                          {'form': AuthenticationForm(),
                           'error': 'Неверные данные для входа!'})
        else:
            login(request, user)
            return redirect('home')

def logoutuser(request):
    logout(request)
    return redirect('home')

abilitys/templates/abilitys/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Portfolio</title>
</head>
<body>
    <nav>
         <div class="logo">
            <a href="{% url 'home' %}">
                <img src="{% static 'abilitys/images/logo-.png' %}" alt="My Logo" width="71" height="68">
            </a>
        </div>
        <div class="username">
            {% if user.is_authenticated %}
                <p>Hello,</p><span class="user">{{ user.username }}</span><p>!</p>
            {% endif %}
        </div>
        <ul class="nav-links">
            <li><a class="links" href="{% url 'home' %}">HOME</a></li>
            <li><a class="links" href="{% url 'projects:project_list' %}">PROJECTS</a></li>
            <li><a class="links" href="{% url 'contact:contact_page' %}">CONTACT</a></li>
            {% if user.is_authenticated %}
                {% csrf_token %}
                <li><a class="links" href="{% url 'projects:logout' %}">EXIT</a></li>
            {% else %}
                <li><a class="links" href="{% url 'projects:login' %}">LOGIN</a></li>
            {% endif %}
        </ul>
    </nav>

    <div class="content">
        {% block content %}{% endblock %}
    </div>

    <footer>
        <p>&copy; 2023 Zubkov Oleg. All rights reserved.</p>
    </footer>
</body>
</html>

abilitys/templates/abilitys/home.html
{% extends 'abilitys/base.html' %}
{% load static %}

{% block content %}
<div class="home">
    <h1>Welcome to My Portfolio</h1>
    <p>I am a developer showcasing my projects and skills.</p>
    <a href="{% url 'projects:project_list' %}" class="button">View Projects</a>
</div>

<div class="skills">
    <div class="skill">
        <img src="/media/abilitys/images/python-logo-.png" alt="Python Logo">
        <h2>Python</h2>
        <p>Experienced in Python programming with a focus on web development, data analysis, and automation.</p>
    </div>
    <div class="skill">
        <img src="/media/abilitys/images/htmlcss-logo-.png" alt="HTML/CSS Logo">
        <h2>HTML/CSS</h2>
        <p>Proficient in building responsive and visually appealing web interfaces using HTML and CSS.</p>
    </div>
    <div class="skill">
        <img src="/media/abilitys/images/js-logo-.png" alt="Javascript Logo">
        <h2>Javascript</h2>
        <p>Skilled in front-end development with JavaScript, creating dynamic and interactive web applications.</p>
    </div>
</div>
{% endblock %}\

contact/templates/contact/contact_page.html
{% extends 'abilitys/base.html' %}
{% load static %}

{% block content %}

<div class="profile-section">
    <h2>About Me</h2>
    <p>Hello, I'm a developer with a love for coding. Feel free to contact me if you have any questions or inquiries.</p>
    <h3>Links to my social networks:</h3>
    <p><a href="#">Summary</a></p>
    <p><a href="https://github.com/zubkovoleg01" target="_blank">GitHub</a></p>
    <p><a href="https://t.me/russianmurder" target="_blank">Telegram</a></p>
    <p><a href="https://wa.me/89879928013?text=%D0%9F%D1%80%D0%B8%D0%B2%D0%B5%D1%82!%20%F0%9F%91%8B%20%D0%9C%D0%B5%D0%BD%D1%8F%20%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%B5%D1%81%D1%83%D0%B5%D1%82..." target="_blank">WhatsApp</a></p>
</div>


<h2 class="cont">Contact Me</h2>
<form method="POST" class="form-section">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Submit</button>
</form>
{% endblock %}

contact/templates/contact/thank_you.html
{% extends 'abilitys/base.html' %}
{% load static %}

{% block content %}
<div class="thank-you-section">
    <h2>Thank You!</h2>
    <img src="{% static 'contact/images/thank_you_img.png' %}" alt="Thank You Image" class="thank-you-image">
    <p>Your message has been successfully submitted.</p>
    <a href="{% url 'home' %}" class="button">Back to Home</a>
</div>
{% endblock %}


projects/templates/projects/loginuser.html
{% extends 'abilitys/base.html' %}


{% block content %}
<div class="login-form">
    <h2>Login</h2>
    <form method="POST" class="form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn">Login</button>
    </form>
    <p class="signup-link">Don't have an account? <a href="{% url 'projects:signup' %}">Sign up</a></p>
</div>
{% endblock %}

projects/templates/projects/project_detail.html
{% extends 'abilitys/base.html' %}
{% load static %}

{% block content %}
<div class="project-detail">
    <img src="{{ project.image.url }}" alt="{{ project.title }}" class="project-image2">
    <div class="project-info">
        <h2>{{ project.title }}</h2>
        <p>Date: {{ project.date_completed }}</p>
        <p>{{ project.description }}</p>
         {% if user.is_authenticated %}
            <a href="{{ project.download_link }}" class="download-link" target="_blank">Download</a>
        {% else %}
            <p><a href="{% url 'projects:login' %}" class="login-link">Login</a> to download the project!</p>
        {% endif %}
    </div>
    <a href="{% url 'projects:project_list' %}" class="back-button">Back</a>
</div>
{% endblock %}



projects/templates/projects/project_list.html
{% extends 'abilitys/base.html' %}
{% load static %}

{% block content %}
<div class="project-list">
    <h2 class="section-title">List of projects</h2>
    <ul class="project-items">
        {% for project in projects %}
            <li class="project-item">
                <h3 class="project-title"><a class="go_detail" href="{% url 'projects:project_detail' project.id %}">{{ project.title }}</a></h3>
                <p class="project-date">Date: {{ project.date_completed }}</p>
                <p class="project-description">{{ project.description }}</p>
                <img src="{{ project.image.url }}" alt="{{ project.title }}" class="project-image1">
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}



projects/templates/projects/signupuser.html
{% extends 'abilitys/base.html' %}

{% load static %}

{% block content %}
<div class="registration-form">
    <h2>Registration</h2>
    <form method="POST" class="form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn">Register</button>
    </form>
</div>
{% endblock %}
